version: "3"

services:
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-local-data:/var/lib/mysql
      - .:/root/
  fileserver:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
    environment:
      - AZURITE_ACCOUNTS=drezip:z8A+QnfibR5m1ZBOM7t8/FAG8556FpAIgiRXmKqmWz43JoIb0kbzW66/rO1HV+TZzeTFWBM9f1QsJduSeCxuSw==
volumes:
  mysql-local-data: