version: "3"

services:
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-local-data:/var/lib/mysql
      - .:/root/
volumes:
  mysql-local-data: