apiVersion: v1
kind: Service
metadata:
  name: blobstorage
  namespace: {{ .Values.environment }}
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ExternalName
  externalName: drezip.blob.core.windows.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy
  namespace: {{ .Values.environment }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: drezip-frontend
              port:
                number: 80
        - pathType: Prefix
          path: "/api"
          backend:
            service:
              name: drezip-backend
              port:
                number: 80
        - pathType: Prefix
          path: "/images"
          backend:
            service:
              name: blobstorage
              port:
                number: 443
