apiVersion: v1
kind: Service
metadata:
  name: blobstorage
  namespace: {{ .Values.environment }}
spec:
  type: ExternalName
  externalName: aign.blob.core.windows.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy
  namespace: {{ .Values.environment }}
  annotations:
    nginx.ingress.kubernetes.io/client-body-buffer-size: 5M
    nginx.ingress.kubernetes.io/proxy-body-size: "60m"
    cert-manager.io/cluster-issuer: {{ .Values.certIssuer }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: drezip-ch-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: drezip-frontend
              port:
                number: 80
        - pathType: Prefix
          path: /api
          backend:
            service:
              name: drezip-backend
              port:
                number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-blobstorage
  namespace: {{ .Values.environment }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/upstream-vhost: aign.blob.core.windows.net
    cert-manager.io/cluster-issuer: {{ .Values.certIssuer }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: drezip-ch-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /images(/|$)(.*)
            backend:
              service:
                name: blobstorage
                port:
                  number: 443
