apiVersion: v1
kind: ConfigMap
metadata:
  name: drezip-backend-config
  namespace: {{ .Values.environment }}
  labels:
    app: drezip
    type: backend
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.environment }}
  application-{{ .Values.environment }}.properties: |
    spring.datasource.username=drezip_app
    spring.datasource.url=jdbc:mysql://drezip-db:3306/drezip

    spring.flyway.user=drezip_flyway
    spring.flyway.url=jdbc:mysql://drezip-db:3306/drezip

    spring.datasource.hikari.jdbc-url=jdbc:mysql://drezip-db:3306/drezip
    spring.datasource.hikari.username=drezip_app

    # do not load fixtures other than local environment
    spring.flyway.locations=classpath:db/migration

    # file storage
    app.azure-blob-storage-connection-string=DefaultEndpointsProtocol=https;AccountName=drezip;AccountKey=${app.azure-blob-storage-key};EndpointSuffix=core.windows.net
    app.azure-blob-storage-container-name={{ .Values.environment }}

    # optical character recognition service
    app.ocr-url=https://thelab.cognitiveservices.azure.com/vision/v3.1/read/analyze?language=de
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drezip-backend-sa
  namespace: {{ .Values.environment }}
  labels:
    app: drezip
    type: backend
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drezip-backend
  namespace: {{ .Values.environment }}
  labels:
    app: drezip
    type: backend
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: drezip
      type: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drezip
        type: backend
      annotations:
        git-commit: {{ .Values.gitCommit }}
    spec:
      nodeSelector:
        agentpool: apps
      serviceAccountName: drezip-backend-sa
      securityContext:
        # any user
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: backend
        args: [
            'java', '-jar', 'drezip-{{ .Values.appVersion }}.jar',
            '--spring.config.location=/drezip/config/,classpath:/application.properties',
            '--app.azure-blob-storage-key=$(BLOB_STORAGE_KEY)',
            '--app.ocr-key=$(OCR_KEY)',
            '--spring.datasource.hikari.password=$(DREZIP_DB_APP_USER_PW)',
            '--spring.datasource.password=$(DREZIP_DB_APP_USER_PW)',
            '--spring.flyway.password=$(DREZIP_DB_FLYWAY_USER_PW)'
        ]
        livenessProbe:
          httpGet:
            port: 9000
            path: /actuator/health/liveness
        readinessProbe:
          httpGet:
            port: 9000
            path: /actuator/health/readiness
        ports:
          - containerPort: 8080
        envFrom:
          - secretRef:
              name: drezip-backend-secret
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                key: SPRING_PROFILES_ACTIVE
                name: drezip-backend-config
          - name: DREZIP_DB_APP_USER_PW
            valueFrom:
              secretKeyRef:
                key: DREZIP_DB_APP_USER_PW
                name: drezip-db-users-secrets
          - name: DREZIP_DB_FLYWAY_USER_PW
            valueFrom:
              secretKeyRef:
                key: DREZIP_DB_FLYWAY_USER_PW
                name: drezip-db-users-secrets
        volumeMounts:
          - mountPath: /drezip/config
            name: drezip-config-volume
      imagePullSecrets:
        - name: aignn-registry
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: drezip-config-volume
          configMap:
            name: drezip-backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: drezip-backend
  namespace: {{ .Values.environment }}
  labels:
    app: drezip
    type: backend
spec:
  selector:
    app: drezip
    type: backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
