package ch.lucfonjallaz.drezip.bl.receipt

import ch.lucfonjallaz.drezip.bl.receipt.item.ReceiptItemDto
import ch.lucfonjallaz.drezip.bl.receipt.line.LineDto
import java.time.LocalDateTime
import java.util.*

// TODO: The mapping here might result in a lot of queries generated by hibernate. might consider having a look at @NamedEntityGraph
data class ReceiptDto(
        val id: Int,
        val status: ReceiptStatus,
        val imgUrl: String,
        val uploadedAt: Date,
        val angle: Float? = null,
        val total: Float? = null,
        val totalLineId: Int? = null,
        val date: Date? = null,
        val dateLineId: Int? = null,
        var lines: List<LineDto>? = null,
        var items: List<ReceiptItemDto>? = null
)