apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugrequests
  namespace: {{ .Values.environment }}
  labels:
    app: debugrequests
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: debugrequests
  template:
    metadata:
      labels:
        app: debugrequests
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: Always
          name: debugrequests
          ports:
            - containerPort: 8090
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: debugrequests
  namespace: {{ .Values.environment }}
  labels:
    app: debugrequests
spec:
  selector:
    app: debugrequests
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8090
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: debugrequestsproxy
  namespace: {{ .Values.environment }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certIssuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: drezip-ch-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: /debug
            backend:
              service:
                name: debugrequests
                port:
                  number: 80
