package ch.lucfonjallaz.drezip.core

enum class ServiceErrorCode {
    GENERIC,
    INVALID_CREDENTIALS,
    USER_ALREADY_EXISTS,
    ENTITY_NOT_FOUND,
    REGISTRATION_CODE_EXPIRED,
    REGISTRATION_CODE_NOT_MATCHING,
    USER_ALREADY_CONFIRMED
}