apiVersion: apps/v1
kind: Deployment
metadata:
  name: drezip-backend
  namespace: test
  labels:
    app: drezip
    type: backend
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: drezip
      type: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drezip
        type: backend
    spec:
      containers:
      - image: aignn.azurecr.io/drezip/backend:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: backend
        args: [
            'java', '-jar', 'drezip-0.0.1-SNAPSHOT.jar',
            '--spring.config.location=/drezip/config/,classpath:/application.properties',
            '--app.azure-blob-storage-key=$(app.azure-blob-storage-key)',
            '--app.ocr-key=$(app.ocr-key)',
            '--spring.datasource.hikari.password=$(spring.datasource.hikari.password)',
            '--spring.datasource.password=$(spring.datasource.password)',
            '--spring.flyway.password=$(spring.flyway.password)'
        ]
        ports:
          - containerPort: 80
        envFrom:
          - secretRef:
              name: drezip-secret
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                key: SPRING_PROFILES_ACTIVE
                name: drezip-config
        volumeMounts:
          - mountPath: /drezip/config
            name: drezip-config-volume
      imagePullSecrets:
        - name: aignn-registry
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: drezip-config-volume
          configMap:
            name: drezip-config

